---
- hosts: all

  tasks:
    - name: Get disk space
      command: df -h
      register: disk_usage
  
  tasks:
    - name: Check disk space available
      command: df -h / | awk 'NR==2 {print $5}'
      register: disk_usage

   
     
    # Send Discord Message
    - name: Send Discord Message
      uri:
        url: "https://discord.com/api/webhooks/1132694976799715358/4_T5d6jTu1WzRwM-AtzXRD5CgsjBGpKThpUnuazJ0E1ffcVNSV3lqygcXwAqE74VZa-n"
        method: POST
        body_format: json
        body: '{"content": "Disk space on {{ inventory_hostname }} is above 70%!"}'
        headers:
          content-type: application/json
        status_code: 204
      when: disk_usage.stdout[:-1]|int >70
    
